const PRODUCTS = [
  { name: "Cucumber", code: 90 },
  { name: "Cauliflower", code: 56 },
  { name: "Bananas", code: 25 },
  { name: "Carrots", code: 53 },
  { name: "Melon (Yellow)", code: 201 },
  { name: "Parsnips", code: 279 },
  { name: "Broccoli", code: 47 },
  { name: "Pepper (Green)", code: 48 },
  { name: "Pepper (Red)", code: 50 },
  { name: "Pepper (Yellow)", code: 51 },
  { name: "Peppers (Mixed)", code: 49 },
  { name: "Spring Onions", code: 395 },
  { name: "Courgettes (Yellow)", code: 81 },
  { name: "Milk (Oat)", code: 1212 },
  { name: "Lettuce (Lollo Rosso)", code: 187 },
  { name: "Lettuce (Frisee)", code: 179 },
  { name: "Lettuce (Flat)", code: 188 },
  { name: "Lettuce (Baby/Little Gem)", code: 181 },
  { name: "Lettuce (Iceberg)", code: 183 },
  { name: "Lettuce (Lollo Biondi)", code: 184 },
  { name: "Lettuce (Oakleaf)", code: 185 },
  { name: "Lettuce (Radicchio)", code: 186 },
  { name: "Lettuce (Lambs)", code: 189 },
  { name: "Melon (Catalope)", code: 197 },
  { name: "Melon (Galia)", code: 199 },
  { name: "Melon (Water)", code: 200 },
  { name: "Green Beans (Fine)", code: 27 },
  { name: "Chillies (Red)", code: 65 },
  { name: "Chillies (Green)", code: 64 },
  { name: "Sugar Snap", code: 288 },
  { name: "Flat Parsley", code: 277 },
  { name: "Grapefruit (Red)", code: 132 },
  { name: "Grapefruit (White)", code: 131 },
  { name: "Broccoli (Purple Sprouting)", code: 2238 },
  { name: "Cauliflower (Purple/Cape)", code: 39 },
  { name: "Greek Yoghurt (5 Litres)", code: 939 },
  { name: "Mangetout", code: 194 },
  { name: "Celery", code: 57 },
  { name: "Rocket", code: 384 },
  { name: "Bacon", code: 1724 },
  { name: "Butternut Squash", code: 399 },
  { name: "Grapes (Red)", code: 134 },
  { name: "Grapes (White)", code: 135 },
  { name: "Apple (Red/Gala)", code: 4 },
  { name: "Raspberries", code: 380 },
  { name: "Blueberries", code: 36 },
  { name: "Blackberries", code: 35 },
  { name: "Plums", code: 292 },
  { name: "Kiwi", code: 172 },
  { name: "Oranges (Medium)", code: 267 },
  { name: "Oranges (Large)", code: 266 },
  { name: "Oranges (Juicing)", code: 269 },
  { name: "Tomato (Plum)", code: 1297 },
  { name: "Milk (SS – 2ltr)", code: 234 },
  { name: "Milk (FF – 2ltr)", code: 227 },
  { name: "Milk (Skimmed – 2ltr)", code: 231 },
  { name: "Milk (Buttermilk - 1ltr)", code: 1182 },
  { name: "Frozen Peas", code: 115 },
  { name: "Mushrooms (Oyster)", code: 255 },
  { name: "Mushy Peas (2.65kg)", code: 1203 },
  { name: "Mushrooms (Dried Mixed)", code: 972 },
  { name: "Mangoes", code: 195 },
  { name: "Margarine (Stork Baking)", code: 941 },
  { name: "Micro Fennel", code: 208 },
  { name: "Micro Green Basil", code: 203 },
  { name: "Micro Cress Celery", code: 206 },
  { name: "Micro Cress Garlic Chives", code: 209 },
  { name: "Micro Cress Mizzuna", code: 212 },
  { name: "Micro Cress Red Chard", code: 218 },
  { name: "Micro Sea Rosemary", code: 2197 },
  { name: "Lettuce (Baby Leaf PUNNET)", code: 239 },
  { name: "Beans (Mixed Bean Salad)", code: 1829 },
  { name: "Micro Parsley", code: 214 },
  { name: "Micro Red Amaranth", code: 202 },
  { name: "Micro Red/Purple Basil", code: 204 },
  { name: "Micro Red Vein Sorrel", code: 222 },
  { name: "Micro Rocket", code: 216 },
  { name: "Micro Thai Basil", code: 225 },
  { name: "Micro Thyme", code: 215 },
  { name: "Micro Watercress", code: 226 },
  { name: "Cabbage (White)", code: 41 },
  { name: "Cabbage (Red)", code: 42 },
  { name: "Chinese Leaf", code: 40 },
  { name: "Baby Leaf/Mixed Leaf", code: 24 },
  { name: "Kohl Rabi", code: 173 },
  { name: "Lettuce (Cos)", code: 180 },
  { name: "Aubergines", code: 16 },
  { name: "Tomato (Cherry)", code: 411 },
  { name: "Onions (Brown Small)", code: 261 },
  { name: "Cheddar (Mature 1kg)", code: 818 },
  { name: "Tomato (Round)", code: 419 },
  { name: "50s Baking Potatoes", code: 295 },
  { name: "Potatoes (New)", code: 303 },
  { name: "Strawberry", code: 405 },
  { name: "Grated Cheese", code: 807 },
  { name: "Hispi", code: 43 },
  { name: "Cheese (Soft/Cream)", code: 930 },
  { name: "Mushroom (Chestnut)", code: 245 },
  { name: "Mushroom (Flat)", code: 246 },
  { name: "Mushroom (Button)", code: 244 },
  { name: "Mushroom (Closed)", code: 243 },
  { name: "Mushroom (Soup)", code: 253 },
  { name: "Onion Seeds (Nigella/Black)", code: 640 },
  { name: "Spinach (Packets)", code: 393 },
  { name: "Satsumas", code: 389 },
  { name: "Butter (Salted)", code: 925 },
  { name: "Vinegar (Cider)", code: 1489 },
  { name: "Onion (Red)", code: 263 },
  { name: "Margarine (Butter/Soft Spread)", code: 940 },
  { name: "Radish", code: 688 },
  { name: "Gooseberry", code: 127 },
  { name: "Mozzarella Balls", code: 821 },
  { name: "Vegetable Oil", code: 1484 },
  { name: "Flour (Dark Ground Cotswold Flour)", code: 1686 },
  { name: "Tomato (Golden Coeur De Boeuf)", code: 2535 },
  { name: "Greek Yoghurt (500g)", code: 938 },
  { name: "Chips (10mm)", code: 2455 },
  { name: "Mascarpone (250g)", code: 943 },
  { name: "Honey (2kg)", code: 1108 },
  { name: "Anchovies (Flat)", code: 1969 },
  { name: "Tuna (1.8kg)", code: 1475 },
  { name: "Greek Yoghurt (1kg)", code: 2328 },
  { name: "Cream (Clotted – 1kg)", code: 929 },
  { name: "Butter Portions (100)", code: 925 },
  { name: "Natural Yoghurt (454g)", code: 951 },
  { name: "Cheese Biscuits (Jacobs)", code: 1125 },
  { name: "Potato (Agria – Maris Pipers with Note)", code: 304 },
  { name: "Potato (Washed White)", code: 311 },
  { name: "Cheese (Barbers)", code: 1617 },
  { name: "Milk (SS Pergal)", code: 235 },
  { name: "Orange Juice (Fresh)", code: 1535 },
  { name: "Cheese Biscuits (Thomas Fudge)", code: 766 },
  { name: "Chips (19mm)", code: 2456 },
  { name: "Butter (Salted)", code: 926 },
  { name: "Food Containers", code: 2695 },
  { name: "Nuts (Mixed Smokehouse)", code: 2081 },
  { name: "Radish (Prepacked)", code: 378 },
  { name: "Baked Beans (Heinz – 2.62kg)", code: 1101 },
  { name: "Tuna (800g)", code: 2062 },
  { name: "Lovage", code: 143 },
  { name: "Peppers (Roasted)", code: 1345 },
  { name: "Tomatoes (Chopped)", code: 1745 },
  { name: "Watercress (UK)", code: 89 },
  { name: "Basil (25g)", code: 152 },
  { name: "Bayleaf (25g)", code: 153 },
  { name: "Chervil (25g)", code: 154 },
  { name: "Chives (25g)", code: 155 },
  { name: "Coriander (25g)", code: 156 },
  { name: "Curly Parsley (25g)", code: 2601 },
  { name: "Dill (25g)", code: 157 },
  { name: "Limes/Lemons", code: 176 },
  { name: "Flat Parsley (25g)", code: 158 },
  { name: "Marjoram (25g)", code: 159 },
  { name: "Mint (25g)", code: 160 },
  { name: "Oregano (25g)", code: 161 },
  { name: "Rosemary (25g)", code: 162 },
  { name: "Sage (25g)", code: 163 },
  { name: "Sorrel (25g)", code: 164 },
  { name: "Tarragon (25g)", code: 166 },
  { name: "Lemon Thyme (100g)", code: 432 },
  { name: "Lemon Verbena (100g)", code: 512 },
  { name: "Sorrell (100g)", code: 149 },
  { name: "Tomatoes (Heritages Baby PUNNET)", code: 2325 }
];

export default PRODUCTS;
